.TH GETINSTRS 1 "2009-12-16"
.SH NAME
.B getinstrs
\- extracts TrueType instructions for one or more glyphs from a font.
.SH SYNOPSIS
.B getinstrs [options]
.IR fontfile
.IR glyphs ...
.SH DESCRIPTION
.B getinstrs
calls the FontForge Python extension to extract instructions from a
TrueType font (either .ttf or .sfd) and print them to stdout (redirect
to capture them in a file). By default the instructions are printed
as an Xgridfit glyph program. Use the \-r, \-\-raw command-line option
to print them as "raw" instructions instead, or use \-x, \-\-xgridfit
to enclose the glyph program(s) in an <xgridfit> element, making a
complete, valid Xgridfit program.
.hy .
.SH OPTIONS
.IP "\-h, \-\-help"
Display a help message and exit.
.IP "\-r, \-\-raw"
Print "raw" instructions instead of Xgridfit glyph programs.
.IP "\-x, \-\-xgridfit"
Print XML declaration and <xgridfit> element, making a complete,
valid Xgridfit program.
.SH SEE ALSO
.BR xgridfit (1),
.BR fontforge (1),
.BR python (1)
.\" .br
.SH AUTHOR
.B getinstrs
was written by Peter Baker
.nh
<psb6m@virginia.edu>.
.hy 
.PP
This manual page was written by Peter Baker
